$(function(){
	$(".showImg").hover(function(){
		$(".hideImg").show().hover(function(){
			$(this).show()
		},function(){
			$(this).hide()
		})
	},function(){
		$(".hideImg").hide()
	})
})
